#!/bin/sh

package='tufte-latex'
class='tufte-handout.cls'

set -e # exit on first error

# Verify prerequisites:

if test $# -ne 1
then
  echo "Usage: $0 VERSION"
  exit 1
fi

version=$1

if ! echo $version | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$"
then
  echo "VERSION should be of the form 1.2.5 (major.minor.revision)"
  exit 1
fi

if ! grep -q $version $class
then
  echo "Error: version skew. '$version' does not match that in class"
  grep -H ProvidesClass $class
  exit 1
fi

if ! grep -q $version History.txt
then
  echo "Error: no release notes for '$version' found in History.txt"
  grep -H $version History.txt
  exit 1
fi

class_date=`date +%Y/%m/%d` # (with slashes)

if ! grep -q $class_date $class
then
  echo "Error: date skew. '$class_date' does not match that in class"
  grep -H ProvidesClass $class
  exit 1
fi 

history_date=`date +%Y-%m-%d` # (with dashes)

if ! grep -q $history_date History.txt
then
  echo "Error: '$history_date' not found in History.txt"
  grep -H $history_date History.txt
  exit 1
fi

# Refresh sample document

pdflatex sample-handout >  refresh-sample.log
bibtex   sample-handout >> refresh-sample.log
pdflatex sample-handout >> refresh-sample.log
pdflatex sample-handout >> refresh-sample.log
rm -f sample-handout.{aux,log,out} refresh-sample.log

# Make bundle

mkdir -p pkg/$package-$version
tar cf - `cat Manifest.txt` | ( cd pkg/$package-$version && tar xf - )
zip -rq pkg/$package-$version.zip pkg/$package-$version

cat << MESSAGE

`openssl dgst -sha1 pkg/$package-$version.zip`

Don't forget to create an SVN tag (after committing changes),

 svn cp -m'To tag release $version.' \\
   https://$package.googlecode.com/svn/trunk \\
   https://$package.googlecode.com/svn/tags/rel_$version

and upload the zip file,

 http://code.google.com/p/$package/downloads/list
 http://ctan.org/upload

MESSAGE
